# Generated by Django 5.1.3 on 2026-04-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='metricsample',
            new_name='performance_run_id_833565_idx',
            old_name='tasks_metri_run_id_52b55f_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='csv_file',
        ),
        migrations.AddField(
            model_name='task',
            name='csv_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
