# Generated by Django 5.1.3 on 2026-04-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_backend_listener_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendlistenerconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='biz_category',
            field=models.CharField(choices=[('shared', '共享课'), ('ai', 'AI 事业中心'), ('kg', 'KG 知识图谱'), ('custom', '定制')], default='shared', max_length=20),
        ),
    ]
