# Generated by Django 5.1.3 on 2026-05-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_taskrun_step3'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
