# Generated by Django 5.1.3 on 2026-05-07 09:24

from django.db import migrations, models


def migrate_service_name_to_list(apps, schema_editor):
    """把已有 service_name 的非空值搬到 service_names 列表里。"""
    Task = apps.get_model('performance', 'Task')
    for t in Task.objects.exclude(service_name=''):
        t.service_names = [t.service_name]
        t.save(update_fields=['service_names'])


def noop_reverse(apps, schema_editor):
    # 反向迁移时丢失多选信息无解，留空让 RemoveField 自己处理
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_task_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='service_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(migrate_service_name_to_list, noop_reverse),
        migrations.RemoveField(
            model_name='task',
            name='service_name',
        ),
    ]
