# Generated by Django 5.1.3 on 2026-05-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0009_service_names_multiselect'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=120)),
                ('ip', models.CharField(max_length=45)),
                ('port', models.PositiveIntegerField(default=9100)),
                ('token', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('idle', 'Idle'), ('busy', 'Busy'), ('lost', 'Lost')], db_index=True, default='pending', max_length=12)),
                ('cpu_cores', models.PositiveSmallIntegerField(default=0)),
                ('memory_gb', models.FloatField(default=0)),
                ('max_vusers', models.PositiveIntegerField(default=100, help_text='单台并发上限（plan 决定 100，可在 admin 调）')),
                ('jmeter_version', models.CharField(blank=True, max_length=20)),
                ('orchestrator_type', models.CharField(default='docker', help_text='k8s / docker / 其他', max_length=12)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddField(
            model_name='taskrun',
            name='load_generators',
            field=models.ManyToManyField(blank=True, related_name='runs', to='performance.loadgenerator'),
        ),
    ]
