# Generated by Django 5.1.3 on 2026-05-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0010_load_generator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='服务名，task.service_names 引用此值。', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='服务说明。')),
                ('base_url', models.CharField(blank=True, help_text='服务对外地址（仅展示）。', max_length=500)),
                ('grafana_url', models.CharField(blank=True, help_text='Grafana dashboard 根 URL（兜底，没配 grafana_panels 时用）。后端 v1.4 query Grafana HTTP API 时也用这个根 URL。', max_length=500)),
                ('pinpoint_app', models.CharField(blank=True, help_text='Pinpoint application name。', max_length=100)),
                ('arthus_endpoint', models.CharField(blank=True, help_text='Arthas tunnel endpoint（v1.5 接入用，当前 placeholder）。', max_length=500)),
                ('grafana_panels', models.JSONField(blank=True, default=list, help_text='Grafana panel 列表，每项 {"name": ..., "url": ..., "type": "service"|"trace"|"jvm"}。service → 服务面板 tab；trace → 链路面板 tab；jvm → JVM tab（v1 dump 按钮 disabled）。')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '被压测服务',
                'verbose_name_plural': '被压测服务',
                'ordering': ['name'],
            },
        ),
    ]
