# Generated by Django 5.1.3 on 2026-05-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0011_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinpointConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='开关：run 终态时是否调 Pinpoint API 拉慢 trace。关闭时 pinpoint_collector 立即返回，TracePanelsTab 显示占位。')),
                ('base_url', models.CharField(blank=True, help_text='Pinpoint Web 服务 URL，例：http://pinpoint.internal.com:8079。留空时即使 enabled=True 也跳过。', max_length=500)),
                ('auth_token', models.CharField(blank=True, help_text='Bearer token（按客户实际鉴权方式调整）。客户内网无鉴权时留空。', max_length=500)),
                ('request_timeout_sec', models.IntegerField(default=10, help_text='HTTP 请求超时秒数；超时后该次 collect 静默失败，不污染 run 状态。')),
            ],
            options={
                'verbose_name': 'Pinpoint 全局配置',
                'verbose_name_plural': 'Pinpoint 全局配置',
            },
        ),
        migrations.CreateModel(
            name='RunPinpointTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='对应 task.service_names 中的服务名。', max_length=100)),
                ('trace_id', models.CharField(help_text='Pinpoint transaction ID。', max_length=200)),
                ('elapsed_ms', models.IntegerField(help_text='整 trace 总耗时（ms）。')),
                ('start_ts_ms', models.BigIntegerField(help_text='trace 起始时刻（ms epoch）。')),
                ('exception_type', models.CharField(blank=True, help_text='Pinpoint 标识的异常类型（如 java.net.SocketTimeoutException），无异常留空。', max_length=200)),
                ('pinpoint_detail_url', models.CharField(blank=True, help_text='Pinpoint 原生 transactionInfo 详情页 URL，前端外链跳转看 span tree。', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinpoint_traces', to='performance.taskrun')),
            ],
            options={
                'verbose_name': 'Pinpoint 慢 trace',
                'verbose_name_plural': 'Pinpoint 慢 trace',
                'ordering': ['-elapsed_ms'],
                'indexes': [models.Index(fields=['run', 'service_name'], name='performance_run_id_3d9da4_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'trace_id'), name='unique_pinpoint_trace_per_run')],
            },
        ),
    ]
