# Generated by Django 5.1.3 on 2026-05-09 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0012_pinpointconfig_runpinpointtrace'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunEventAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ramp_done', 'ramp 完成（所有 vu 起来）'), ('hold_start', 'hold 开始（稳态期）'), ('shutdown_start', 'shutdown 开始'), ('first_error', '第一次出现错误'), ('error_rate_breached', '错误率破阈值'), ('p99_sla_breached', 'P99 破 SLA')], help_text='事件类型；按 RunEventType TextChoices 取值。', max_length=40)),
                ('ts_ms', models.BigIntegerField(help_text='事件时刻（ms epoch）；与 InfluxDB 时序对齐。')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='额外参数，例：error_rate_breached → {"threshold":0.8,"actual":0.95}；p99_sla_breached → {"sla_ms":500,"actual_ms":680}。')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_anchors', to='performance.taskrun')),
            ],
            options={
                'verbose_name': 'Run 事件锚点',
                'verbose_name_plural': 'Run 事件锚点',
                'ordering': ['ts_ms'],
                'indexes': [models.Index(fields=['run', 'event_type'], name='performance_run_id_4f8cd3_idx'), models.Index(fields=['run', 'ts_ms'], name='performance_run_id_fab268_idx')],
            },
        ),
    ]
