# Generated by Django 5.1.3 on 2026-05-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0013_runeventanchor'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='error_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
