# Generated by Django 5.1.3 on 2026-05-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0014_taskrun_error_breakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runeventanchor',
            name='event_type',
            field=models.CharField(choices=[('ramp_done', 'ramp 完成（所有 vu 起来）'), ('hold_start', 'hold 开始（稳态期）'), ('shutdown_start', 'shutdown 开始'), ('first_sample', '首条 sample 落地（JMeter 真正开跑）'), ('first_error', '第一次出现错误'), ('first_5xx', '第一次出现 5xx 服务端错误'), ('error_rate_breached', '错误率破阈值'), ('p99_sla_breached', 'P99 破 SLA'), ('throughput_plateau', '吞吐拐点（加 VU 但 RPS 不涨）')], help_text='事件类型；按 RunEventType TextChoices 取值。', max_length=40),
        ),
    ]
