# Generated by Django 5.1.3 on 2026-05-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0015_alter_runeventanchor_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
