# Generated by Django 5.1.3 on 2026-05-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0016_taskrun_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='jmx_hash_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='thread_groups_config_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
