# Generated by Django 5.1.3 on 2026-05-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0017_taskrun_jmx_hash_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
