# Generated by Django 5.1.3 on 2026-05-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0018_taskrun_deleted_at_taskrun_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='runtime_log',
            field=models.TextField(blank=True),
        ),
    ]
