# Generated by Django 5.1.3 on 2026-05-25 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0019_taskrun_runtime_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concurrency', models.JSONField(blank=True, default=dict)),
                ('latency_breakdown', models.JSONField(blank=True, default=dict)),
                ('error_breakdown_ts', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='performance.taskrun')),
            ],
        ),
        migrations.CreateModel(
            name='RunErrorAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_code', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=0)),
                ('sample_message', models.TextField(blank=True)),
                ('sample_failure_message', models.TextField(blank=True)),
                ('sample_url', models.TextField(blank=True)),
                ('sample_response_body', models.TextField(blank=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_aggregates', to='performance.taskrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run'], name='performance_run_id_cac038_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'response_code', 'label'), name='uniq_run_err_agg')],
            },
        ),
        migrations.CreateModel(
            name='RunSamplerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('total', models.PositiveIntegerField(default=0)),
                ('success', models.PositiveIntegerField(default=0)),
                ('error', models.PositiveIntegerField(default=0)),
                ('avg_ms', models.FloatField(default=0)),
                ('min_ms', models.FloatField(default=0)),
                ('max_ms', models.FloatField(default=0)),
                ('p50_ms', models.FloatField(default=0)),
                ('p90_ms', models.FloatField(default=0)),
                ('p99_ms', models.FloatField(default=0)),
                ('avg_rps', models.FloatField(default=0)),
                ('avg_bytes', models.FloatField(default=0)),
                ('top_errors', models.JSONField(blank=True, default=list)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampler_stats', to='performance.taskrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run'], name='performance_run_id_50fff8_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'label'), name='uniq_run_sampler')],
            },
        ),
    ]
