# Generated by Django 5.1.3 on 2026-05-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0019_taskrun_runtime_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrometheusDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='数据源名称，如 ali-k8s-new、ali-k8s-online。', max_length=100, unique=True)),
                ('url', models.CharField(help_text='Prometheus 兼容 API 根地址（到 /api/v1 之前的部分）。阿里云 ARMS 示例：https://cn-hangzhou.arms.aliyuncs.com:9443/api/v1/prometheus/xxx/cn-hangzhou', max_length=500)),
                ('auth_token', models.CharField(blank=True, help_text='Bearer token（内网免认证时留空）。', max_length=500)),
                ('enabled', models.BooleanField(default=True, help_text='禁用后前端不展示该数据源。')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prometheus 数据源',
                'verbose_name_plural': 'Prometheus 数据源',
                'ordering': ['name'],
            },
        ),
    ]
