# Generated by Django 5.1.3 on 2026-05-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0020_runanalysis_runerroraggregate_runsamplerstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='runanalysis',
            name='latency_overall',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
