# Generated by Django 5.1.3 on 2026-05-20 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0020_prometheusdatasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='prometheus_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='performance.prometheusdatasource'),
        ),
    ]
