# Generated by Django 5.1.3 on 2026-05-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0021_runanalysis_latency_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='is_baseline',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='keep',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
