# Generated by Django 5.1.3 on 2026-06-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0021_task_prometheus_source'),
        ('performance', '0022_taskrun_is_baseline_taskrun_keep'),
    ]

    operations = [
    ]
