# Generated by Django 5.1.3 on 2026-06-08 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0023_merge_20260601_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunServiceDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
                ('servermap', models.JSONField(blank=True, default=dict)),
                ('diagnosis', models.JSONField(blank=True, default=dict)),
                ('prometheus', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_diagnoses', to='performance.taskrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'service'), name='unique_run_service_diagnosis')],
            },
        ),
    ]
