# Generated by Django 5.1.3 on 2026-06-09 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0024_runservicediagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunArthasCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=200)),
                ('pod', models.CharField(blank=True, max_length=200)),
                ('command', models.CharField(max_length=300)),
                ('output', models.TextField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arthas_captures', to='performance.taskrun')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
