# Generated by Django 5.1.3 on 2026-06-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0025_runarthascapture'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadgenerator',
            name='jmeter_home',
            field=models.CharField(blank=True, help_text='ssh 型：机器上 JMeter 目录，如 /usr/local/apache-jmeter-5.6.3', max_length=300),
        ),
        migrations.AddField(
            model_name='loadgenerator',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='loadgenerator',
            name='ssh_user',
            field=models.CharField(blank=True, default='root', max_length=64),
        ),
        migrations.AddField(
            model_name='loadgenerator',
            name='transport',
            field=models.CharField(db_index=True, default='agent', help_text='agent / ssh', max_length=8),
        ),
    ]
