# Generated by Django 5.1.3 on 2026-06-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0026_loadgenerator_jmeter_home_loadgenerator_ssh_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runanalysis',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='runanalysis',
            name='ai_summary_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
