# Generated by Django 5.1.3 on 2026-06-11 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0027_runanalysis_ai_summary_runanalysis_ai_summary_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='定时任务名称', max_length=120)),
                ('schedule_type', models.CharField(choices=[('once', '一次性'), ('recurring', '周期性')], default='once', help_text='一次性 / 周期性', max_length=12)),
                ('run_at', models.DateTimeField(blank=True, help_text='【一次性】执行的日期时间', null=True)),
                ('cron', models.CharField(blank=True, help_text='【周期性】cron 表达式（5 段，按 Asia/Shanghai 时区）。例：0 2 * * * = 每天凌晨 2 点；*/30 * * * * = 每 30 分钟；0 9 * * 1 = 每周一 9 点', max_length=120)),
                ('enabled', models.BooleanField(default=True, help_text='禁用后不再触发')),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, help_text='下次触发时间（保存时自动算，调度单一真相）', null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, help_text='最近一次触发失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(blank=True, help_text='最近一次触发创建的 run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='performance.taskrun')),
                ('load_generators', models.ManyToManyField(blank=True, help_text='用哪些压力机跑（留空 = 主控本机直跑 LOCAL_FALLBACK）', to='performance.loadgenerator')),
                ('task', models.ForeignKey(help_text='要定时跑的压测任务（须已完成 Step 2 配置）', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='performance.task')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
