# Generated by Django 5.1.3 on 2026-06-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0028_taskschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backendlistenerconfig',
            options={'verbose_name': '后端监听器配置', 'verbose_name_plural': '后端监听器配置'},
        ),
        migrations.AlterModelOptions(
            name='environment',
            options={'ordering': ['-is_default', 'name'], 'verbose_name': '压测环境', 'verbose_name_plural': '压测环境'},
        ),
        migrations.AlterModelOptions(
            name='loadgenerator',
            options={'ordering': ['-registered_at'], 'verbose_name': '压力机', 'verbose_name_plural': '压力机'},
        ),
        migrations.AlterModelOptions(
            name='metricsample',
            options={'ordering': ['timestamp'], 'verbose_name': '指标采样', 'verbose_name_plural': '指标采样'},
        ),
        migrations.AlterModelOptions(
            name='runeventanchor',
            options={'ordering': ['ts_ms'], 'verbose_name': '运行事件锚点', 'verbose_name_plural': '运行事件锚点'},
        ),
        migrations.AlterModelOptions(
            name='runpinpointtrace',
            options={'ordering': ['-elapsed_ms'], 'verbose_name': 'Pinpoint 慢调用', 'verbose_name_plural': 'Pinpoint 慢调用'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': '压测任务', 'verbose_name_plural': '压测任务'},
        ),
        migrations.AlterModelOptions(
            name='taskrun',
            options={'ordering': ['-started_at'], 'verbose_name': '执行记录', 'verbose_name_plural': '执行记录'},
        ),
    ]
