# Generated by Django 5.1.3 on 2026-09-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0029_alter_backendlistenerconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArthasConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='关闭后 Arthas 相关端点直接返回未启用，前端不展示终端入口。')),
                ('http_base_url', models.CharField(blank=True, help_text='zapp-server HTTP 地址，留空用默认 https://zapp-server.zhihuishu.com', max_length=500)),
                ('ws_base_url', models.CharField(blank=True, help_text='zapp-server WebSocket 地址，留空用默认 wss://zapp-server.zhihuishu.com', max_length=500)),
                ('account', models.CharField(blank=True, help_text='zapp-server 登录账号。留空时回落到环境变量 ZAPP_ACCOUNT。', max_length=200)),
                ('password', models.CharField(blank=True, help_text='zapp-server 登录密码。留空时回落到环境变量 ZAPP_PASSWORD。', max_length=200)),
                ('request_timeout_sec', models.IntegerField(default=10, help_text='HTTP 请求超时秒数。')),
            ],
            options={
                'verbose_name': 'Arthas 全局配置',
                'verbose_name_plural': 'Arthas 全局配置',
            },
        ),
    ]
