# Generated by Django 5.1.3 on 2026-09-15 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0030_arthasconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='落盘文件名（scripts/ 下）', max_length=255)),
                ('original_name', models.CharField(help_text='用户上传时的原始文件名', max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_files', to='performance.task')),
            ],
            options={
                'verbose_name': '任务附件',
                'verbose_name_plural': '任务附件',
                'ordering': ['original_name'],
                'unique_together': {('task', 'filename')},
            },
        ),
    ]
